- name: Test post please ignore
  hosts: localhost
  vars:
    - goversion_preferred: "go version go1.24.1*"
    - tfversion_preferred: "Terraform v1.6*"
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - neovim
          - git
          - tree
          - xsel
          - xclip
        become: true
        become_user: root
        state: present
      when: ansible_distribution == 'Ubuntu'
    
    - name: Check for Golang version
      command: go version
      register: golang_version
      ignore_errors: yes

    - name: Install Golang Binary
      when: golang_version["stdout"] != goversion_preferred
        ansible.builtin.apt:
          - name: golang
            become_user: root
            become: true
    
    - name: Check for Terraform version
      command: terraform -version
      register: tf_version
      ignore_errors: yes
      
    - name: Install Terraform Binary
      when: tf_version["stdout"] != tfversion_preferred
        ansible.builtin.apt:
          - name: terraform
            



    - name: Copy zshrc folder to user folder'
      ansible.builtin.file:

