---
- name: Remove previous installation of go
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Create temp directory 
  ansible.builtin.file:
    path: /tmp/go/extracted
    state: directory

- name: Download go tar file
  ansible.builtin.get_url:
    url: 'https://go.dev/dl/go{{ go_version }}.{{ go_platform }}.tar.gz'
    dest: /tmp/go
    mode: '0755'

- name: Unarchive go
  ansible.builtin.unarchive:
    copy: false
    src: '/tmp/go/go{{ go_version }}.{{ go_platform }}.tar.gz'
    dest: '/tmp/go/extracted'
    creates: '/tmp/go/extracted/go'

- name: Move extracted file to local folder
  ansible.builtin.shell: mv /tmp/go/extracted/* /usr/local/

- name: Remove unneeded tar file
  ansible.builtin.file: 
    path: /tmp/go
    state: absent
