---

- name: Check for Ubuntu distro
  ansible.builtin.fail:
    msg: "Only good for Ubuntu. Please try again."
  when: ansible_facts['distribution'] != "Ubuntu"

- name: Install packages
  ansible.builtin.apt:
    name:
      - neovim
      - git
      - tree
      - xsel
      - xclip
    state: present
    update_cache: true
  become: true

- name: Copy zshrc file to user folder'
  ansible.builtin.copy:
    src: /roles/workstation/files/zshrc
    dest: /home/{{ lookup('env', 'USER') }}/.zshrc
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0774'

###
# Check for version of Go lang, if not preferred version, 
###

- name: Check for Golang version
  ansible.builtin.command: go version
  register: golang_version
  changed_when: no
  ignore_errors: true

- name: Install Golang
  ansible.builtin.import_tasks:
    file: golang.yml
  when: golang_version.stdout != goversion_preferred




#- name: Check for and install Terraform
#  ansible.builtin.import_tasks:
#    file: terraform.yml

