
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(git kubectl helm zsh-autosuggestions zsh-syntax-hightlighting)

source $ZSH/oh-my-zsh.sh

alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'

export PATH=$PATH:/usr/local/go/bin
